sudo: required
services:
  - docker

before_install:
  - docker build -t mead1600/docker-react -f Dockerfile.dev .

script:
  -  docker run -e CI=true mead1600/docker-react npm run test

deploy:
  provider: elasticbeanstock
  region: "us-east-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-424116003825"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
